name: flutter_io
version: 0.0.1
dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  path: any
  test: ^0.12.13
  url_launcher:
  path_provider:
